POSIX shell compliance, fix couple of logic errors

diff --git a/check_mysql_slavestatus b/check_mysql_slavestatus
--- a/check_mysql_slavestatus
+++ b/check_mysql_slavestatus
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #########################################################################
 # Script:       check_mysql_slavestatus.sh                              #
 # Author:       Claudio Kuenzler www.claudiokuenzler.com                #
@@ -70,140 +70,141 @@ Attention: The DB-user you type in must have CLIENT REPLICATION rights on the DB
     GRANT REPLICATION CLIENT on *.* TO 'nagios'@'%' IDENTIFIED BY 'secret';
 "
 
-STATE_OK=0      # define the exit code if status is OK
-STATE_WARNING=1     # define the exit code if status is Warning (not really used)
-STATE_CRITICAL=2    # define the exit code if status is Critical
-STATE_UNKNOWN=3     # define the exit code if status is Unknown
-export PATH=$PATH:/usr/local/bin:/usr/bin:/bin # Set path
+state_ok=0      # define the exit code if status is OK
+state_warning=1     # define the exit code if status is Warning (not really used)
+state_critical=2    # define the exit code if status is Critical
+state_unknown=3     # define the exit code if status is Unknown
 crit="No"       # what is the answer of MySQL Slave_SQL_Running for a Critical status?
 ok="Yes"        # what is the answer of MySQL Slave_SQL_Running for an OK status?
 
 for cmd in mysql awk grep [; do
-    if ! `which ${cmd} &>/dev/null`; then
-        echo "UNKNOWN: This script requires the command '${cmd}' but it does not exist; please check if command exists and PATH is correct"
-        exit ${STATE_UNKNOWN}
+    if ! which "$cmd" > /dev/null 2>&1; then
+        echo "UNKNOWN: This script requires the command '$cmd' but it does not exist; please check if command exists and PATH is correct"
+        exit $state_unknown
     fi
 done
 
 # Check for people who need help - aren't we all nice ;-)
 #########################################################################
-if [ "${1}" = "--help" -o "${#}" = "0" ]; then
-    echo -e "${help}"
-    exit 1
+if [ "$1" = "--help" ] || [ "$#" = "0" ]; then
+    echo "$help"
+    exit $state_uknown
 fi
 
 # Important given variables for the DB-Connect
 #########################################################################
-while getopts "H:P:u:p:s:w:c:h" Input; do
-    case ${Input} in
-    H)
-        host=${OPTARG}
+while getopts "H:P:u:p:s:w:c:h" option; do
+    case $option in
+    "H")
+        host=$OPTARG
         ;;
-    P)
-        port=${OPTARG}
+    "P")
+        port=$OPTARG
         ;;
-    u)
-        user=${OPTARG}
+    "u")
+        user=$OPTARG
         ;;
-    p)
-        password=${OPTARG}
+    "p")
+        password=$OPTARG
         ;;
-    s)
-        connection=\"${OPTARG}\"
+    "s")
+        connection=\"$OPTARG\"
         ;;
-    w)
-        warn_delay=${OPTARG}
+    "w")
+        warn_delay=$OPTARG
         ;;
-    c)
-        crit_delay=${OPTARG}
+    "c")
+        crit_delay=$OPTARG
         ;;
-    h)
-        echo -e "${help}";
-        exit 1
-        ;;
-    \?)
-        echo "Wrong option given. Please use options -H for host, -P for port, -u for user and -p for password"
-        exit 1
+    "h" | "?")
+        echo "$help";
+        exit $state_unknown
         ;;
     esac
 done
 
-# Connect to the DB server and check for informations
-#########################################################################
 # Check whether all required arguments were passed in
-if [ -z "${host}" -o -z "${port}" -o -z "${user}" -o -z "${password}" ]; then
-    echo -e "${help}"
-    exit ${STATE_UNKNOWN}
-fi
-# Connect to the DB server and store output in vars
-ConnectionResult=`mysql -h ${host} -P ${port} -u ${user} --password=${password} -e "show slave ${connection} status\G" 2>&1`
-if [ -z "`echo "${ConnectionResult}" |grep Slave_IO_State`" ]; then
-    echo -e "CRITICAL: Unable to connect to server ${host}:${port} with username '${user}' and given password"
-    exit ${STATE_CRITICAL}
-fi
-check=`echo "${ConnectionResult}" |grep Slave_SQL_Running: | awk '{print $2}'`
-checkio=`echo "${ConnectionResult}" |grep Slave_IO_Running: | awk '{print $2}'`
-masterinfo=`echo "${ConnectionResult}" |grep  Master_Host: | awk '{print $2}'`
-delayinfo=`echo "${ConnectionResult}" |grep Seconds_Behind_Master: | awk '{print $2}'`
-
-# Output of different exit states
-#########################################################################
-if [ ${check} = "NULL" ]; then
-    echo "CRITICAL: Slave_SQL_Running is answering NULL"
-    exit ${STATE_CRITICAL}
+if [ -z "$host" ] || [ -z "$port" ] || [ -z "$user" ] || [ -z "$password" ]; then
+    echo "$help"
+    exit $state_unknown
 fi
 
-if [ ${check} = ${crit} ]; then
-    echo "CRITICAL: ${host}:${port} Slave_SQL_Running: ${check}"
-    exit ${STATE_CRITICAL}
-fi
-
-if [ ${checkio} = ${crit} ]; then
-    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"
-    exit ${STATE_CRITICAL}
-fi
-
-if [ ${checkio} = "Connecting" ]; then
-    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"
-    exit ${STATE_CRITICAL}
-fi
-
-if [ ${check} = ${ok} ] && [ ${checkio} = ${ok} ]; then
-    # Delay thresholds are set
-    if [[ -n ${warn_delay} ]] && [[ -n ${crit_delay} ]]; then
-        if ! [[ ${warn_delay} -gt 0 ]]; then
-            echo "Warning threshold must be a valid integer greater than 0"
-            exit $STATE_UNKNOWN
-        fi
-        if ! [[ ${crit_delay} -gt 0 ]]; then
-            echo "Warning threshold must be a valid integer greater than 0"
-            exit $STATE_UNKNOWN
-        fi
-        if [[ -z ${warn_delay} ]] || [[ -z ${crit_delay} ]]; then
-            echo "Both warning and critical thresholds must be set"
-            exit $STATE_UNKNOWN
-        fi
-        if [[ ${warn_delay} -gt ${crit_delay} ]]; then
-            echo "Warning threshold cannot be greater than critical"
-            exit $STATE_UNKNOWN
-        fi
-
-        if [[ ${delayinfo} -ge ${crit_delay} ]]; then
-            echo "CRITICAL: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"
-            exit ${STATE_CRITICAL}
-        elif [[ ${delayinfo} -ge ${warn_delay} ]]; then
-            echo "WARNING: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"
-            exit ${STATE_WARNING}
-        else
-            echo "OK: Slave SQL running: ${check} Slave IO running: ${checkio} / master: ${masterinfo} / slave is ${delayinfo} seconds behind master | delay=${delayinfo}s"
-            exit ${STATE_OK}
-        fi
-    else
-        # Without delay thresholds
-        echo "OK: Slave SQL running: ${check} Slave IO running: ${checkio} / master: ${masterinfo} / slave is ${delayinfo} seconds behind master | delay=${delayinfo}s"
-        exit ${STATE_OK}
+if [ -n "$warn_delay" ] || [ -n "$crit_delay" ]; then
+    if ! [ "$warn_delay" -gt 0 ]; then
+        echo "Warning threshold must be a valid integer greater than 0"
+        exit $state_unknown
+    fi
+    if ! [ "$crit_delay" -gt 0 ]; then
+        echo "Warning threshold must be a valid integer greater than 0"
+        exit $state_unknown
+    fi
+    if [ -z "$warn_delay" ] || [ -z "$crit_delay" ]; then
+        echo "Both warning and critical thresholds must be set"
+        exit $state_unknown
+    fi
+    if [ "$warn_delay" -gt "$crit_delay" ]; then
+        echo "Warning threshold cannot be greater than critical"
+        exit $state_unknown
     fi
 fi
 
-echo "UNKNOWN: should never reach this part (Slave_SQL_Running is ${check}, Slave_IO_Running is ${checkio})"
-exit ${STATE_UNKNOWN}
+# Connect to the DB server and check for informations
+#########################################################################
+
+# Connect to the DB server and store output in vars
+connectionresult=$(mysql -h "$host" -P "$port" -u "$user" --password="$password" -e "show slave $connection status\G" 2>&1)
+iostate=$(echo "$connectionresult" | grep Slave_IO_State: | awk '{print $2}')
+check=$(echo "$connectionresult" | grep Slave_SQL_Running: | awk '{print $2}')
+checkio=$(echo "$connectionresult" | grep Slave_IO_Running: | awk '{print $2}')
+masterinfo=$(echo "$connectionresult" | grep  Master_Host: | awk '{print $2}')
+delayinfo=$(echo "$connectionresult" | grep Seconds_Behind_Master: | awk '{print $2}')
+
+# Output of different exit states
+#########################################################################
+if [ -z "$iostate" ]; then
+    echo "CRITICAL: Unable to connect to server $host:$port with username '$user' and given password"
+    exit $state_critical
+fi
+
+if [ "$check" = "NULL" ]; then
+    echo "CRITICAL: Slave_SQL_Running is answering NULL"
+    exit $state_critical
+fi
+
+if [ "$check" = "$crit" ]; then
+    echo "CRITICAL: $host:$port Slave_SQL_Running: $check"
+    exit $state_critical
+fi
+
+if [ "$checkio" = "$crit" ]; then
+    echo "CRITICAL: $host Slave_IO_Running: $checkio"
+    exit $state_critical
+fi
+
+if [ "$checkio" = "Connecting" ]; then
+    echo "CRITICAL: $host Slave_IO_Running: $checkio"
+    exit $state_critical
+fi
+
+if [ "$check" = "$ok" ] && [ "$checkio" = "$ok" ]; then
+    # Delay thresholds are set
+    if [ -n "$warn_delay" ] && [ -n "$crit_delay" ]; then
+        if [ "$delayinfo" -ge "$crit_delay" ]; then
+            echo "CRITICAL: Slave is $delayinfo seconds behind Master | delay=$delayinfo"
+            exit $state_critical
+        elif [ "$delayinfo" -ge "$warn_delay" ]; then
+            echo "WARNING: Slave is $delayinfo seconds behind Master | delay=$delayinfo"
+            exit $state_warning
+        else
+            echo "OK: Slave SQL running: $check Slave IO running: $checkio / master: $masterinfo / slave is $delayinfo seconds behind master | delay=$delayinfo"
+            exit $state_ok
+        fi
+    else
+        # Without delay thresholds
+        echo "OK: Slave SQL running: $check Slave IO running: $checkio / master: $masterinfo / slave is $delayinfo seconds behind master | delay=$delayinfo"
+        exit $state_ok
+    fi
+fi
+
+echo "UNKNOWN: should never reach this part (Slave_SQL_Running is $check, Slave_IO_Running is $checkio)"
+exit $state_unknown
