more cosmetic changes

diff --git a/check_mysql_slavestatus b/check_mysql_slavestatus
--- a/check_mysql_slavestatus
+++ b/check_mysql_slavestatus
@@ -53,10 +53,22 @@
 #########################################################################
 # Usage: ./check_mysql_slavestatus.sh -H dbhost -P port -u dbuser -p dbpass -s connection -w integer -c integer
 #########################################################################
-help="\ncheck_mysql_slavestatus.sh (c) 2008-2014 GNU GPLv2 licence
-Usage: check_mysql_slavestatus.sh -H host -P port -u username -p password [-s connection] [-w integer] [-c integer]\n
-Options:\n-H Hostname or IP of slave server\n-P Port of slave server\n-u Username of DB-user\n-p Password of DB-user\n-s Connection name (optional, with multi-source replication)\n-w Delay in seconds for Warning status (optional)\n-c Delay in seconds for Critical status (optional)\n
-Attention: The DB-user you type in must have CLIENT REPLICATION rights on the DB-server. Example:\n\tGRANT REPLICATION CLIENT on *.* TO 'nagios'@'%' IDENTIFIED BY 'secret';"
+help="
+check_mysql_slavestatus.sh (c) 2008-2014 GNU GPLv2 licence
+Usage: check_mysql_slavestatus.sh -H host -P port -u username -p password [-s connection] [-w integer] [-c integer]
+
+Options:
+-H Hostname or IP of slave server
+-P Port of slave server
+-u Username of DB-user
+-p Password of DB-user
+-s Connection name (optional, with multi-source replication)
+-w Delay in seconds for Warning status (optional)
+-c Delay in seconds for Critical status (optional)
+
+Attention: The DB-user you type in must have CLIENT REPLICATION rights on the DB-server. Example:
+    GRANT REPLICATION CLIENT on *.* TO 'nagios'@'%' IDENTIFIED BY 'secret';
+"
 
 STATE_OK=0      # define the exit code if status is OK
 STATE_WARNING=1     # define the exit code if status is Warning (not really used)
@@ -66,10 +78,8 @@ export PATH=$PATH:/usr/local/bin:/usr/bin:/bin # Set path
 crit="No"       # what is the answer of MySQL Slave_SQL_Running for a Critical status?
 ok="Yes"        # what is the answer of MySQL Slave_SQL_Running for an OK status?
 
-for cmd in mysql awk grep [
-do
-    if ! `which ${cmd} &>/dev/null`
-    then
+for cmd in mysql awk grep [; do
+    if ! `which ${cmd} &>/dev/null`; then
         echo "UNKNOWN: This script requires the command '${cmd}' but it does not exist; please check if command exists and PATH is correct"
         exit ${STATE_UNKNOWN}
     fi
@@ -77,26 +87,42 @@ done
 
 # Check for people who need help - aren't we all nice ;-)
 #########################################################################
-if [ "${1}" = "--help" -o "${#}" = "0" ];
-then
-    echo -e "${help}";
-    exit 1;
+if [ "${1}" = "--help" -o "${#}" = "0" ]; then
+    echo -e "${help}"
+    exit 1
 fi
 
 # Important given variables for the DB-Connect
 #########################################################################
-while getopts "H:P:u:p:s:w:c:h" Input;
-do
+while getopts "H:P:u:p:s:w:c:h" Input; do
     case ${Input} in
-    H) host=${OPTARG};;
-    P) port=${OPTARG};;
-    u) user=${OPTARG};;
-    p) password=${OPTARG};;
-    s) connection=\"${OPTARG}\";;
-    w) warn_delay=${OPTARG};;
-    c) crit_delay=${OPTARG};;
-    h) echo -e "${help}"; exit 1;;
-    \?) echo "Wrong option given. Please use options -H for host, -P for port, -u for user and -p for password"
+    H)
+        host=${OPTARG}
+        ;;
+    P)
+        port=${OPTARG}
+        ;;
+    u)
+        user=${OPTARG}
+        ;;
+    p)
+        password=${OPTARG}
+        ;;
+    s)
+        connection=\"${OPTARG}\"
+        ;;
+    w)
+        warn_delay=${OPTARG}
+        ;;
+    c)
+        crit_delay=${OPTARG}
+        ;;
+    h)
+        echo -e "${help}";
+        exit 1
+        ;;
+    \?)
+        echo "Wrong option given. Please use options -H for host, -P for port, -u for user and -p for password"
         exit 1
         ;;
     esac
@@ -105,7 +131,7 @@ done
 # Connect to the DB server and check for informations
 #########################################################################
 # Check whether all required arguments were passed in
-if [ -z "${host}" -o -z "${port}" -o -z "${user}" -o -z "${password}" ];then
+if [ -z "${host}" -o -z "${port}" -o -z "${user}" -o -z "${password}" ]; then
     echo -e "${help}"
     exit ${STATE_UNKNOWN}
 fi
@@ -123,39 +149,59 @@ delayinfo=`echo "${ConnectionResult}" |grep Seconds_Behind_Master: | awk '{print
 # Output of different exit states
 #########################################################################
 if [ ${check} = "NULL" ]; then
-    echo "CRITICAL: Slave_SQL_Running is answering NULL"; exit ${STATE_CRITICAL};
+    echo "CRITICAL: Slave_SQL_Running is answering NULL"
+    exit ${STATE_CRITICAL}
 fi
 
 if [ ${check} = ${crit} ]; then
-    echo "CRITICAL: ${host}:${port} Slave_SQL_Running: ${check}"; exit ${STATE_CRITICAL};
+    echo "CRITICAL: ${host}:${port} Slave_SQL_Running: ${check}"
+    exit ${STATE_CRITICAL}
 fi
 
 if [ ${checkio} = ${crit} ]; then
-    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"; exit ${STATE_CRITICAL};
+    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"
+    exit ${STATE_CRITICAL}
 fi
 
 if [ ${checkio} = "Connecting" ]; then
-    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"; exit ${STATE_CRITICAL};
+    echo "CRITICAL: ${host} Slave_IO_Running: ${checkio}"
+    exit ${STATE_CRITICAL}
 fi
 
 if [ ${check} = ${ok} ] && [ ${checkio} = ${ok} ]; then
     # Delay thresholds are set
     if [[ -n ${warn_delay} ]] && [[ -n ${crit_delay} ]]; then
-        if ! [[ ${warn_delay} -gt 0 ]]; then echo "Warning threshold must be a valid integer greater than 0"; exit $STATE_UNKNOWN; fi
-        if ! [[ ${crit_delay} -gt 0 ]]; then echo "Warning threshold must be a valid integer greater than 0"; exit $STATE_UNKNOWN; fi
-        if [[ -z ${warn_delay} ]] || [[ -z ${crit_delay} ]]; then echo "Both warning and critical thresholds must be set"; exit $STATE_UNKNOWN; fi
-        if [[ ${warn_delay} -gt ${crit_delay} ]]; then echo "Warning threshold cannot be greater than critical"; exit $STATE_UNKNOWN; fi
+        if ! [[ ${warn_delay} -gt 0 ]]; then
+            echo "Warning threshold must be a valid integer greater than 0"
+            exit $STATE_UNKNOWN
+        fi
+        if ! [[ ${crit_delay} -gt 0 ]]; then
+            echo "Warning threshold must be a valid integer greater than 0"
+            exit $STATE_UNKNOWN
+        fi
+        if [[ -z ${warn_delay} ]] || [[ -z ${crit_delay} ]]; then
+            echo "Both warning and critical thresholds must be set"
+            exit $STATE_UNKNOWN
+        fi
+        if [[ ${warn_delay} -gt ${crit_delay} ]]; then
+            echo "Warning threshold cannot be greater than critical"
+            exit $STATE_UNKNOWN
+        fi
 
-        if [[ ${delayinfo} -ge ${crit_delay} ]]
-        then echo "CRITICAL: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"; exit ${STATE_CRITICAL}
-        elif [[ ${delayinfo} -ge ${warn_delay} ]]
-        then echo "WARNING: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"; exit ${STATE_WARNING}
-        else echo "OK: Slave SQL running: ${check} Slave IO running: ${checkio} / master: ${masterinfo} / slave is ${delayinfo} seconds behind master | delay=${delayinfo}s"; exit ${STATE_OK};
+        if [[ ${delayinfo} -ge ${crit_delay} ]]; then
+            echo "CRITICAL: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"
+            exit ${STATE_CRITICAL}
+        elif [[ ${delayinfo} -ge ${warn_delay} ]]; then
+            echo "WARNING: Slave is ${delayinfo} seconds behind Master | delay=${delayinfo}s"
+            exit ${STATE_WARNING}
+        else
+            echo "OK: Slave SQL running: ${check} Slave IO running: ${checkio} / master: ${masterinfo} / slave is ${delayinfo} seconds behind master | delay=${delayinfo}s"
+            exit ${STATE_OK}
         fi
     else
         # Without delay thresholds
         echo "OK: Slave SQL running: ${check} Slave IO running: ${checkio} / master: ${masterinfo} / slave is ${delayinfo} seconds behind master | delay=${delayinfo}s"
-        exit ${STATE_OK};
+        exit ${STATE_OK}
     fi
 fi
 
